Vectors module
Rogozin-high-school/sat_monitoring_system pull request #34
Opened 2018-02-18 19:09 UTC by shaiTheKimhi

2018-02-18 19:23 UTC, ron-popov commented
Oh hell no, there will be no visual studio config files in my repo

2018-02-18 20:55 UTC, yotam180 commented
I must admit I never bothered testing the code's validity as I believe the chances it will useful _somewhen_ reach zero.

Sorry about that. I'll be getting to reviewing the fixes you made right now.

2018-02-18 21:03 UTC, yotam180 requested changes
Those code changes do not solve the issues that this PR claims to do. Please relate to Ron's and my comments.

2018-02-18 21:03 UTC, yotam180 commented on Modules/Vector/.vs/ProjectSettings.json
> +{
Remove this file from staging and add it to _.gitignore_ to prevent it from getting to others' computers (as Ron has already written)

2018-02-18 21:03 UTC, yotam180 commented on Modules/Vector/.vs/VSWorkspaceState.json
> +{
Same. Actually, apply for the entire _.vs_ folder.

2018-02-18 21:03 UTC, yotam180 commented on Modules/Vector/Vector2D.py
> +    def distance_to(self, vector:vector2D) -> float:
Is it considered fixing the problem or uglifying the line?

SPACES.

And add quotes around `vector2D` (e.g. `"vector2D"`) so Python does forward references (prevents the `NameError`)

2018-02-18 21:03 UTC, yotam180 commented on Modules/Vector/Vector2D.py
> +    def __add__(self, vector):
Again, I would not suggest removing the type hints at all. Just make them use forward references and not backward ones.

2018-02-18 21:03 UTC, yotam180 commented on Modules/Vector/Vector2D.py
> +    def scalar_mul(self,vector):
`scalar_mul(self, vector)` -> `dot(self, vector)`

2018-02-18 21:03 UTC, yotam180 commented on Modules/Vector/Vector3D.py
> +    def distance_to(self, vector) -> float:
Again. This is _not_ solving the problem, this is hiding it.

2018-02-18 21:03 UTC, yotam180 commented on Modules/Vector/Vector3D.py
> +    def scalar_mul(self,vector):
`scalar_mul(self, vector)` -> `dot(self, vector)`

Let's keep the terminology correct.

2018-02-18 21:05 UTC, yotam180 commented
Oh, and I don't like the description of the PR. It should explain what's **in this PR** and not what's wrong with **other PRs**

Also commented on the previous PR. You can relate or ignore.

2018-02-19 18:38 UTC, yotam180 requested changes
Can you relate to the other comments, too? Not all my requests were filled.

But we **are** getting closer and closer to a merge.

Oh, and don't forget @ron-popov, you can review those PRs too.

2018-02-19 18:38 UTC, yotam180 commented on Modules/Vector/Vector2D.py
> +    def __add__(self, vector:'vector2D'):
Can you add some spacing between operands and operators? I think I mentioned it beforehand.

`vector:'vector2D'` -> `vector : 'vector2D'`

2018-02-19 18:38 UTC, yotam180 commented on Modules/Vector/.vs/ProjectSettings.json
> +{
Can you relate to that comment, too?

2018-02-19 18:54 UTC, ron-popov commented
Have you though about using a premade vector math library ? @yotam180 suggested we use numpy and there is and issue regarding this ( issue #31 )

2018-02-20 08:52 UTC, yotam180 approved these changes

2018-02-20 08:52 UTC, merged

2018-02-20 13:25 UTC, yotam180 commented
Just to mention I still don't like the spacing