updated Control Tester
Rogozin-high-school/sat_monitoring_system pull request #50
Opened 2018-03-14 14:34 UTC by shaiTheKimhi

2018-03-14 16:22 UTC, ron-popov requested changes

2018-03-14 16:22 UTC, ron-popov commented on Modules/Control/Control.py
> +__circle_time = 1 * 60
How about setting these values as constants in a config file ?

2018-03-14 16:22 UTC, ron-popov commented on Tests/Control.py
> +from ..Modules.Satprot import satprot
Can you change the name of the module to something more descriptive ?

2018-03-16 06:22 UTC, shaiTheKimhi commented on Tests/Control.py
> +from ..Modules.Satprot import satprot
This is yotam's module.
maybe @yotam180 can?

2018-03-20 15:36 UTC, yotam180 commented
Someone resolve the conflicts with this PR before someone else reviews it again. @ron-popov @shaiTheKimhi @Rogozin-high-school/satellite-contributors

2018-03-23 11:37 UTC, ron-popov commented
@shaiTheKimhi Can you resolve the conflict ? All of the code here is yours

2018-03-24 14:05 UTC, shaiTheKimhi commented
This branch was started before the master was changed.
Combined with the fact that these changes were not tested with the simulation makes me close this pull request.
@yotam180 should fix the Tester with me so it would work with the simulation as I had a problem connecting to the simulation through satprot.

2018-03-24 14:05 UTC, closed without merging

2018-03-24 14:30 UTC, yotam180 commented
.........

2018-03-28 13:20 UTC, ron-popov commented
@shaiTheKimhi Can i delete this branch ?

2018-03-28 13:21 UTC, yotam180 commented
Don't ask, just do it.